version: '2.18.1'

services:
  db:
    image: postgres:latest
    restart: always
    volumes:
      - postgresql_data:/var/lib/postgresql/data
    env_file:
      - ./.env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
volumes:
  postgresql_data: